spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/chambercript
spring.datasource.username=root
spring.datasource.password=rootihT22##
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration (Example using Gmail)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
# Your Brevo SMTP Login (usually your email address registered with Brevo)
spring.mail.username=9abbe3001@smtp-brevo.com
# Your Master Password or a generated SMTP Key from the Brevo Dashboard
spring.mail.password=xsmtpsib-c21c398501808ada05e0743f28dbeab2adce546ef1c60e85b44ace720f30d2ee-3pnNi2gerkvHyq3O

# Enable authentication and TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


app.mail.sender=contact@ontocriptit.com

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Hide the Spring Security UserDetailsService auto-config warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR