spring.application.name=backend

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration (Example using Gmail)
spring.mail.host=${mail_host}
spring.mail.port=${mail_port}
# Your Brevo SMTP Login (usually your email address registered with Brevo)
spring.mail.username=${mail_username}
# Your Master Password or a generated SMTP Key from the Brevo Dashboard
spring.mail.password=${mail_password}

# Enable authentication and TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


app.mail.sender=${sender_mail}

# JWT Configuration
application.security.jwt.secret-key=${jwt_secret}
application.security.jwt.expiration=${jwt_expiration_milliseconds}

# Hide the Spring Security UserDetailsService auto-config warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR


bunny.storage.zone=${bunnynet_storage_zone_name}
bunny.storage.key=${bunnynet_storage_access_key}
bunny.storage.url=${bunnynet_storage_base_url}
bunny.pullzone.url=${bunnynet_storage_cdn_url}


# Text.lk SMS API Configuration
textlk.api.url=${text_lk_api_url}
textlk.api.token=${text_lk_api_token}
textlk.sender.id=${text_lk_sender_id}

# Enable Scheduling (For automated jobs)
spring.task.scheduling.pool.size=5

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.base-url=${base_url}

spring.jpa.show-sql=true

logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR

